### ISSUE TITLE
Invoke and Query Api Endpoint

### ISSUE THREAD

**Issue by KG-DI-KXNG** [softwaremill/fablo-rest#35]
These endpoint not working properly or not responding.. it keep requesting for hours please elaborate on the proper procedure to invoke and query chaincode

**Comment by Hejwo** [comment]
Hello,
could you post additional information?  
It would be great to have:  
- your `fablo-config.json` or description how did you set up the network.
- http requests that where made. Preferably in `curl` format

**Comment by KG-DI-KXNG** [comment]
I'm using the the default fabric-config-talk.json, launched perfect however trying to invoke the chain code but just keeps requesting

**Comment by Hejwo** [comment]
Hi,
sorry for delay. I've prepared scenario that you can try yourself to verify everything:
1. Check that you don;t have any other active containers (sometimes exposed ports may overlap ):
`docker ps` - result should be empty
2. Create new fablo network with sample chaincode:
`fablo init rest node` - sholud create basic fablo-config and sample chaincode in current directory
3. Run the network
`fablo up` - should run the network and end with "Done! Enjoy your fresh network"

Next we can try fablo-rest:
4. Login as admin of org1 
```
curl --request POST \
  --url http://localhost:8800/user/enroll \
  --header 'Authorization: Bearer ' \
  --data '{"id": "admin", "secret": "adminpw"}'
```
you should get response with unique token. something like 
```
{"token":"c13c8640-6c77-11ec-a036-93295d59ebf9-admin"}
```
5. Let's try to invoke chaincode: 
```
curl --request POST \
    --url http://localhost:8800/invoke/my-channel1/chaincode1 \
    --header 'Authorization: Bearer c13c8640-6c77-11ec-a036-93295d59ebf9-admin' \
    --data '{"method": "KVContract:put", "args": "[]" }'
```

**Comment by dzikowski** [comment]
Could you also provide the command you use to start `fablo-rest` and env vars provided? It might be an issue with the config, when Fablo REST cannot connect discoverers

**Comment by KG-DI-KXNG** [comment]
`{
  "$schema": "https://github.com/softwaremill/fablo/releases/download/0.3.0/schema.json",
  "networkSettings": {
    "fabricVersion": "2.3.2",
    "tls": true
  },
  "orgs": [
    {
      "organization": {
        "name": "Orderer",
        "domain": "root.com"
      },
      "orderers": [
        {
          "groupName": "group1",
          "type": "raft",
          "instances": 1
        }
      ]
    },
    {
      "organization": {
        "name": "Org1",
        "domain": "org1.com"
      },
      "peer": {
        "instances": 2,
        "anchorPeerInstances": 2
      }
    },
    {
      "organization": {
        "name": "Org2",
        "domain": "org2.com"
      },
      "peer": {
        "instances": 2,
        "anchorPeerInstances": 2
      }
    }
  ],
  "channels": [
    {
      "name": "my-channel1",
      "orgs": [
        {
          "name": "Org1",
          "peers": [
            "peer0",
            "peer1"
          ]
        },
        {
          "name": "Org2",
          "peers": [
            "peer0",
            "peer1"
          ]
        }
      ]
    },
    {
      "name": "my-channel2",
      "orgs": [
        {
          "name": "Org1",
          "peers": [
            "peer1"
          ]
        },
        {
          "name": "Org2",
          "peers": [
            "peer1"
          ]
        }
      ]
    }
  ],
  "chaincodes": [
    {
      "name": "chaincode1",
      "version": "0.0.1",
      "lang": "node",
      "channel": "my-channel1",
      "endorsement": "OR('Org1MSP.member', 'Org2MSP.member')",
      "directory": "./chaincode-kv-node",
      "privateData": [
        {
          "name": "private-collection",
          "orgNames": [
            "Org1",
            "Org2"
          ]
        }
      ]
    }
  ]
}
`

**Comment by KG-DI-KXNG** [comment]
I'm using postman instead of curl

**Comment by KG-DI-KXNG** [comment]
![Screenshot 2022-01-03 085520](https://user-images.githubusercontent.com/84394726/147938920-a287b1c0-4a3b-4258-967a-9a50be9ebfe0.jpg)

**Comment by dzikowski** [comment]
Hi @KG-DI-KXNG, I have some ideas that might help you.

First, it seems that you try to run Fablo REST standalone, since you don't have it in your `fablo-config.json` file. The easiest way to run it Fablo REST to provide it in tools for organization, so you may try to update the `Org1` in `fablo-config.json` as follows:  `{ "organization": {...}, "peer": {...}, "tools": { "fabloRest": true }`. Then Fablo REST for this organization will be available at 8801 port. I just found out that we should have more information about it in the docs, sorry for that -- we are going to update it.

If you want to run it standalone, try to start Fablo REST with the following command, after your Fablo network started:

```
#!/usr/bin/env bash

# provide value from fablo-target/fabric-docker/.env
# from variable COMPOSE_PROJECT_NAME
network=fablo_network_202201031559

docker run \
  -e MSP_ID="Org1MSP" \
  -e FABRIC_CA_URL="http://ca.org1.com:7054" \
  -e FABRIC_CA_NAME="ca.org1.com" \
  -e AS_LOCALHOST=false \
  -e DISCOVERY_URLS=grpcs://peer0.org1.com:7041,grpcs://peer1.org1.com:7042,grpcs://peer0.org2.com:7061,grpcs://peer1.org2.com:7062 \
  -e DISCOVERY_TLS_CA_CERT_FILES=/crypto/org1.com/peers/peer0.org1.com/tls/ca.crt,/crypto/org1.com/peers/peer1.org1.com/tls/ca.crt,/crypto/org2.com/peers/peer0.org2.com/tls/ca.crt,/crypto/org2.com/peers/peer1.org2.com/tls/ca.crt \
  -p "8000:8000" \
  -v /your/absolute/path/to/fablo-target/fabric-config/crypto-config/peerOrganizations:/crypto:ro \
  --network="${network}_basic" \
  -d \
  --rm \
  softwaremill/fablo-rest:0.1.0

```

(in this case Fablo REST will be available on 8000 port)

If none of this works, please provide the command(s) you use to start Fablo REST and logs of Fablo REST container. And we will dig deeper to find the cause of this issue.

If some of proposed solutions work, let us know and feel free to close this issue.

Our TODOs are:
- improve documentation on Fablo REST - https://github.com/hyperledger-labs/fablo/issues/271
- return meaningful status codes when discovery service cannot connect - #37

**Comment by KG-DI-KXNG** [comment]
Got it working but invoking and querying on port 8800 doesn't work but port 8801 works perfectly

**Comment by dzikowski** [comment]
Great to hear that :-)

By the way, we are going to release the version 1.0.0 today or tomorrow, with a bunch of new features. Feel free to check it if you want.

**Comment by jerry-98** [comment]
> Got it working but invoking and querying on port 8800 doesn't work but port 8801 works perfectly

Hi I am also facing the same problem

**Comment by jerry-98** [comment]
I have also added "tools": { "fabloRest": true }
Enroll admin is working but login is invocation is not happening with no response for a long time.

**Comment by jerry-98** [comment]
> These endpoint not working properly or not responding.. it keep requesting for hours please elaborate on the proper procedure to invoke and query chaincode

Same problem here
