### ISSUE TITLE
Adding users to network

### ISSUE THREAD

**Issue by jerry-98** [softwaremill/fablo-rest#38]
1. When we add user to network, are they added to wallet?
2. Where can we view all the users of the network.
3. Can we add attributes of users to the network

**Comment by dzikowski** [comment]
Hi @jerry-98, aswering to your questions:

1. No, we don't support wallets in Fablo-REST right now, we just keep cached identities in memory for a short period of time
2. As an enrolled admin you can GET /user/identities, see https://github.com/softwaremill/fablo-rest#get-useridentities
3. No, we don't support it yet. If you want to do it, you can use original Fabric CA REST API

**Comment by dzikowski** [comment]
@AbhishekBhargav99 thanks for your comment. We will continue this discussion about compatibility with Fabric samples in https://github.com/hyperledger-labs/fablo/issues/285
